apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8091
      protocol: TCP
      name: http
  selector:
    app: product-service
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-nodeport
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      nodePort: 30090
      protocol: TCP
      name: http
  selector:
    app: product-service