apiVersion: v1
kind: Service
metadata:
  name: product-microservice-service
  labels:
    app: product-microservice
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: product-microservice
---
apiVersion: v1
kind: Service
metadata:
  name: product-microservice-nodeport
  labels:
    app: product-microservice
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: product-microservice

